import { Card, Hero } from "@/components";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import clientPromise from "../lib/mongodb";
import axios from "axios";
import { Project } from "@/types/api_responses";

export async function getStaticProps() {
  const response = await fetch("http://localhost:3000/api/projects");
  const data = await response.json();

  return {
    props: {
      projects: data.projects,
    },
  };
}

interface HomeProps {
  projects: Project[];
}

const Home: React.FC<HomeProps> = ({ projects }) => {
  return (
    <main className="home">
      <Head>
        <title>Nikola Mirilo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/NM.png" />
      </Head>
      <Hero
        title="Empowering IT projects to success"
        subtitle="Utilizing my skills in project management and programming to drive successful results by effective planning and executing projects, delivering on deadlines and goals, and developing customized solutions through programming."
        image="/images/office.png"
      />
      <div className="cards-container">
        {projects
          ? projects.map((project, idx) => {
              return (
                <Card
                  key={idx}
                  id={project.id}
                  title={project.title}
                  image={project.image}
                  subtitle="This is my project, I worked on this project"
                />
              );
            })
          : null}
      </div>
    </main>
  );
};
export default Home;
